name: ci

on:
  push:
    branches:
      - 'master'

jobs: # Här nedanför kommer det som skall utföras när min action triggas
  # build: 
  #   runs-on: ubuntu-latest # Miljön min solution skall byggas i 
  #   steps: 
  #   - name: Checkout
  #     uses: actions/checkout@v2 
  #   - name: Setup .NET 
  #     uses: actions/setup-dotnet@v1 
  #     with:
  #       dotnet-version: 5.0.x
  #   - name: Restore 
  #     run: dotnet restore SimpleWebHalloWorld.sln 
  #   - name: Build
  #     run: dotnet build --no-restore SimpleWebHalloWorld.sln # Bygger min solution SpacePark utan att köra restore igen
     
  docker:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2.7.0
      #   with:
      #     push: true
      #     context: ${ {env.working-directory} }/PROJECT_DIR
      #     tags: |
      #       ghcr.io/DITT_USER_NAME/PROJECT:latest
      #       ghcr.io/DITT_USER_NAME/PROJECT:${ { github.run_number } }
 
      

        