name: ci

on:
  push:
    branches:
      - 'master'

jobs: # Här nedanför kommer det som skall utföras när min action triggas
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: ${{env.working-directory}}
          tags: |
            ghcr.io/${{ github.actor }}/webapp:latest
            ghcr.io/${{ github.actor }}/webapp:${{ github.run_number }}


     
 
      

        